/**
 * README.md 自动更新工具
 * 用于在多语言翻译完成后自动更新主 README.md 文件
 * 添加翻译语言列表和链接
 */

interface TranslationInfo {
  language: string
  path: string
  translatedContent?: string
}

interface RepositoryInfo {
  owner: string
  name: string
  defaultBranch: string
}

const LANGUAGE_NAMES: Record<string, string> = {
  en: 'English',
  'zh-CN': '简体中文',
  zh: '简体中文',
  'zh-TW': '繁體中文',
  ja: '日本語',
  ko: '한국어',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  ru: 'Русский',
  pt: 'Português',
  it: 'Italiano',
  ar: 'العربية',
  hi: 'हिन्दी',
  nl: 'Nederlands',
  pl: 'Polski',
  tr: 'Türkçe',
  vi: 'Tiếng Việt',
  th: 'ไทย',
  id: 'Bahasa Indonesia',
  ms: 'Bahasa Melayu',
}

/**
 * 从翻译文件路径中提取语言代码
 */
function extractLanguageFromPath(path: string): string | null {
  const match = path.match(/translations\/([a-zA-Z-]+)\//)
  return match ? match[1] : null
}

/**
 * 获取语言名称
 */
function getLanguageName(code: string): string {
  return LANGUAGE_NAMES[code] || code
}

/**
 * 生成多语言翻译列表的 Markdown 内容
 */
export function generateTranslationListMarkdown(
  translations: TranslationInfo[],
  repoInfo: RepositoryInfo
): string {
  if (translations.length === 0) {
    return ''
  }

  // 按语言分组
  const translationsByLang = new Map<string, Set<string>>()

  for (const translation of translations) {
    const lang = translation.language
    if (!translationsByLang.has(lang)) {
      translationsByLang.set(lang, new Set())
    }
    translationsByLang.get(lang)!.add(translation.path)
  }

  // 生成 Markdown 内容
  let markdown = `\n## 🌐 Translations / 多语言翻译\n\n`
  markdown += `This repository is available in the following languages:\n\n`

  for (const [lang, paths] of translationsByLang.entries()) {
    const langName = getLanguageName(lang)
    const readmePath = Array.from(paths).find(p =>
      p.toLowerCase().includes('readme')
    )

    if (readmePath) {
      // 计算相对路径
      const relativePath = readmePath.replace(/^translations\/[a-zA-Z-]+\//, '')
      markdown += `- [${langName}](./${readmePath})\n`
    } else {
      markdown += `- ${langName} (Coming soon)\n`
    }
  }

  markdown += `\n---\n\n`

  return markdown
}

/**
 * 更新 README.md 内容，插入或更新多语言翻译列表
 */
export function updateReadmeWithTranslations(
  originalReadme: string,
  translations: TranslationInfo[],
  repoInfo: RepositoryInfo
): string {
  const translationList = generateTranslationListMarkdown(translations, repoInfo)

  if (!translationList) {
    return originalReadme
  }

  // 检查是否已有多语言翻译部分
  const existingSectionRegex = /## 🌐 Translations?[^\n]*[\s\S]*?(?=^## |$)/m
  const hasExistingSection = existingSectionRegex.test(originalReadme)

  if (hasExistingSection) {
    // 替换现有部分
    return originalReadme.replace(existingSectionRegex, translationList)
  }

  // 在多语言翻译部分添加到 README 开头（在第一个标题之后）
  const firstHeaderIndex = originalReadme.indexOf('#')
  if (firstHeaderIndex === -1) {
    // 没有标题，添加到开头
    return translationList + originalReadme
  }

  // 找到第一个标题的结束位置
  const firstHeaderEndIndex = originalReadme.indexOf('\n', firstHeaderIndex)
  if (firstHeaderEndIndex === -1) {
    return originalReadme + translationList
  }

  // 插入到第一个标题之后
  const insertPosition = firstHeaderEndIndex + 1
  return (
    originalReadme.slice(0, insertPosition) +
    translationList +
    originalReadme.slice(insertPosition)
  )
}

/**
 * 生成 README.md 的更新 commit 消息
 */
export function generateReadmeUpdateCommitMessage(
  languages: string[]
): string {
  const langNames = languages.map(lang => getLanguageName(lang)).join(', ')
  return `docs(readme): Update translation list (${langNames})\n\nAuto-generated by GitHub Global`
}
